<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>SquooshPro.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-x64" Version="14.17.1" />
  </ItemGroup>
</Project>
